version: "3"
services:
  sender:
    image: python-send
    deploy:
      mode: global
    depends_on:
      - rabbit
    ports:
      - "80:80"
    networks:
      - debug
  recv:
    image: python-recv
    depends_on:
      - rabbit
    deploy:
      mode: global
    networks:
      - debug

# docker run -p 15672:15672 -p 5672:5672 rabbitmq:3-management
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    deploy:
      replicas: 1
    networks:
      - debug
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - debug
networks:
  debug:
